### ISSUE TITLE
Add BIG-IP user roles

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-ci-docs#291]
// Title: Provide a short but descriptive summary of the issue.

// **Do not include requests for development or report issues with code or products here.** 
This repository contains documentation only.

## Requests
Provide details regarding what you would like to see added to our documentation:

We should specify that the CCs can use any of the following BIG-IP roles:
 -'Administrator', 
-'Resource Adminstrator', and 
-'Manager' 

(These are the names listed in the GUI. The 'Manager' role can be constrained to a particular partition.)

### Environment

- [x ] Cloud Foundry
- [x ] Kubernetes
- [x ] OpenShift
- [x ] Mesos/Marathon)

### Use Case 
(i.e., what are you trying to do that you can't find documentation for?)
N/A

**Comment by jputrino** [comment]
See #380 for additional explanation

**Comment by russokj** [comment]
The restriction on the roles mentioned above is a little complicated at the moment.  See me when it comes time to document.

**Comment by f5yacobucci** [comment]
I think at this point we should just document that in many cases you can use Resource Administrator but you won't get the full functionality of the controllers in kubernetes. A role of Administrator is required to create SSL Profiles from kubernetes Secrets and to also update FDB entries when running in cluster mode.

**Comment by russokj** [comment]
After talking with Ashok, I think we can simplify even more.  We will simply state that, in order to provide full functionality, the controller must be configured with a user that has an Administrator role.
