### ISSUE TITLE
Clarify BIG-IP objects created for ConfigMaps

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-ci-docs#314]
// Title: Provide a short but descriptive summary of the issue.

// **Do not include requests for development or report issues with code or products here.** 
This repository contains documentation only.

## Bugs
Describe the bug in detail: 

- What doc are you reporting an issue with (provide URL)?
http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-manage-bigip-objects.html

- What information is inaccurate? 

- Is information missing?

Yes -- we need to clarify that the Controller enables L4 ingress to the cloud. The CC can help configure on the BIG-IP (from information from within the container environment) such things as:
-vips
-vs
-pools
-nodes
-pool members
-assign ssl/tcp profiles
-create ssl/tcp profiles
-health monitors (health monitor type and send string)
-traffic policies
-iApps (you may need to modify the config map)

ConfigMap "ingress":
-vip
-vs
--ssl profile
--health monitor
--tcp profile
-pool
-node
-pool members

Ingress resource:
-vs (wildcard or maybe vip)
--traffic policies
--ssl profile
--http profile
--tcp profile
-pool
-nodes
-pool members
 
Custom deployment (for something like LTM+ASM):
- iApp --> this configures all the objects

## Requests
Provide details regarding what you would like to see added to our documentation:
We should also consider touching on the difference between "ingress" and "Ingress". 

### Environment

- [ ] Cloud Foundry
- [x] Kubernetes
- [ ] OpenShift
- [ ] Mesos/Marathon)

### Use Case 
(i.e., what are you trying to do that you can't find documentation for?)

**Comment by f5yacobucci** [comment]
In addition to L4 and L7 and ingress versus Ingress we should clarify the ConfigMap frontend section in regards to pool only mode and the ip annotation:
Our docs say:
"If you don’t define bindAddr in the Frontend configuration, you must include it in a Kubernetes Annotation to the ConfigMap."
But then go on to say:
"If you don’t define virtualAddress or bindAddr in the Frontend configuration, the Controller configures and manages pools, pool members, and healthchecks for the Service without a BIG-IP virtual server."

I think the MUST is too strong in the first sentence. Do we mean to say something like "If you don't define bindAddr in the Frontend configuration, you may include it in a Kubernetes Annotation to the ConfigMap."
And then:
"If you prefer to run in pool only mode, you should not define a virtualAddress nor a virtual-server.f5.com/ip annotation."

**Comment by f5yacobucci** [comment]
We also must update naming formats for this release as they've changed. This may effect this document: http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-manage-bigip-objects.html

**Comment by amudukutore** [comment]
Description from JIRA regarding Ingress vs ingress:

In a recent call with a customer we spent some time clarifying a misconception about cloud ingress. The customer was confused about how to create ingress configurations for TCP and UDP configurations. For both the F5 k8s controller and the nginx controller ConfigMap resources (and possibly one day ThirdPartyResource objects) are used in conjunction with Service resources to configure non-HTTP (non-L7) ingress. The customer believed all configuration for cloud ingress should be through the Ingress resource.

We have an opportunity to aid understanding by discussing the concept ingress separated from Ingress resources. There is a difference between lower-case ingress (traffic to resources within the cloud) and upper-case Ingress (a k8s resource used to configure L7 HTTP traffic). Traffic where other protocols and transports (L4, UDP) are controlled via other mechanisms - in our case - a combination of native Services and a specified F5 configuration residing in ConfigMap resources.

All traffic does not route through Ingress resources, these resources only control a specific tier of traffic within the full cloud ingress spectrum.

**Comment by f5yacobucci** [comment]
Provide an Upgrade section (already in progress, discussed offline).

Be sure to mention upgrades may cause service disruption. In cases where features are additive we do our best to prevent any disruption but some changes force destructive changes on the BIG-IP. When possible upgrades should be done in a rolling fashion on BIG-IP active/stand-by device groups.
