### ISSUE TITLE
Need guidance on configuring Container Connectors for High Availability

### ISSUE THREAD

**Issue by sjsharma2001** [F5Networks/f5-ci-docs#350]
// Title: Provide a short but descriptive summary of the issue.
We need to provide guidance/options on how to configure the Container Connectors for high availability.

// **Do not include requests for development or report issues with code or products here.** 
This repository contains documentation only.

## Bugs
Describe the bug in detail: 

- What doc are you reporting an issue with (provide URL)?
Solution docs for all the Container Connectors (Marathon, K8s/OpenShift, CloudFoundry)

- What information is inaccurate? 
None

- Is information missing?
Yes. Guidance/options on how to configure the Container Connectors for high availability.

- Is a code sample incorrect?
No

## Requests
Provide details regarding what you would like to see added to our documentation:

### Environment

- [x] Cloud Foundry
- [x] Kubernetes
- [x] OpenShift
- [x] Mesos/Marathon)

### Use Case 
(i.e., what are you trying to do that you can't find documentation for?)
Configuring Container Connectors for high availability

**Comment by jputrino** [comment]
This issue duplicates #250. Work can be tracked here.

**Comment by pdp2shirts** [comment]
FYI I was just on Phone with Kent Munson. He expects to have a first draft for review by team in next few days.
