### ISSUE TITLE
Clarify DC/OS Enterprise access control steps

### ISSUE THREAD

**Issue by f5yacobucci** [F5Networks/f5-ci-docs#356]
Step 3 under DC/OS Enterprise of this document  f5-ci-docs/docs/marathon/mctlr-authenticate-dcos.rst is unclear.

// **Do not include requests for development or report issues with code or products here.** 
This repository contains documentation only.

## Bugs
Describe the bug in detail: 

- What doc are you reporting an issue with (provide URL)?
https://github.com/F5Networks/f5-ci-docs/blob/master/docs/marathon/mctlr-authenticate-dcos.rst
- What information is inaccurate? 
Step 3 (Define the F5_DC/OS_AUTH_CREDENTIALS JSON blob" doesn't fully describe what to do - after reading this I'm still not sure how to transform or edit the credentials.

This section should be updated and a command documented what should be done here, e.g.) cat $FILE | sed -e ':a;N;$!ba;s/\n/\\n/g' -e 's/"/\\"/g' (or whatever is correct) as I'm not sure if this is right.
The domain expert @edarzins should be able to clarify.

- Is information missing?

- Is a code sample incorrect?

## Requests
Provide details regarding what you would like to see added to our documentation:

### Environment

- [ ] Cloud Foundry
- [ ] Kubernetes
- [ ] OpenShift
- [ ] Mesos/Marathon)

### Use Case 
(i.e., what are you trying to do that you can't find documentation for?)

**Comment by edarzins** [comment]
This is a good place for a complete example, because escaping the quotes and newlines can be tricky.
