### ISSUE TITLE
F5 on different Subnet. Netmask (for example, 255.252.0.0) needs to be corrected.

### ISSUE THREAD

**Issue by mdditt2000** [F5Networks/f5-ci-docs#382]
// Title: OpenShift - F5 on different Subnet. Netmask (for example, 255.252.0.0) needs to be corrected. 

## Bugs
Describe the bug in detail: 
No bug but some document improvements. 

## Requests
- [ ] OpenShift

Basically, when I created the overlay interface in the BIG-IP, I firstly used the same subnet that hostsubnet command generated for the “f5-server” (10.128.4.1/23). It was not working, Pods were able to communicate to the BIG-IP (ping), but BIG-IP was not able to reach any  of the other hostsubnets behind the nodes, and traffic was being sent through default gateway (external interface)
I tried to add routes through the same interface where I have configured the vtep, but it didn’t work neither. It happened the same, BIG-IP not sending the traffic through the tunnel interface, it was sending the traffic at that moment using his self IP as the one on the vtep interface
I tried to add a route through a fake IP on the same vxlan interface (xxx/23 gw 10.128.4.2) and I could see arp request from 10.128.4.1, but as nothing was there in .2, it was failing too.
 
Finally, I added a second interface in the vxlan tunnel with a bigger mask (10.128.4.2/14), getting all overlay subnets “inside” it, and it started working perfectly.
 
Looking into the documentation, it doesn’t seem clear how to build this, and we have different versions of the documentation, commenting slightly different things, as you can see below. Does anybody know which is the way to properly configure this? (in my labo, I have it working too with /14 mask). It would be great too to get this better documented.

Version 1:
http://clouddocs.f5.com/containers/v1/openshift/kctlr-use-bigip-openshift.html
Create a BIG-IP self IP address.

Use an address in the range allocated for the HostSubnet created earlier. This ensures that all VXLAN traffic is correctly routed via the openshift_vxlan tunnel. Assign a subnet mask that matches that of the OpenShift SDN cluster network. In OpenShift Origin 1.4, for example, the default is /14.

Tip - When creating a self IP using the BIG-IP configuration utility, specify the full netmask (for example, 255.252.0.0). -- **Please make the following modification in the documentation.** 

create net self 10.129.2.10/14 allow-service all vlan openshift_vxlan
 
Version 2:
http://clouddocs.f5.com/containers/v2/openshift/kctlr-use-bigip-openshift.html
Create a self IP in the VXLAN¶

Create a self IP address in the VXLAN tunnel. Use an address from the subnet allocated by the OpenShift SDN.

create /net self 10.129.2.3/23 allow-service none vlan openshift_vxlan
Important

The subnet mask you assign to the self IP must match that of the subnet assigned by the OpenShift SDN (in this example, /23).

**Comment by jputrino** [comment]
Hi @mdditt2000 -- We don't actually make updates to the v1 branch any longer (it's been EOL'ed since v2 was released). We can clarify in the v2 version that different OpenShift releases have different requirements and that users should check to make sure they're using the correct netmask before creating the tunnel.
