### ISSUE TITLE
Update releases and versioning page with info for version 1.11 of CIS

### ISSUE THREAD

**Issue by pdp2shirts** [F5Networks/f5-ci-docs#738]
update releases and versioning page to include info on version 1.11 of CIS

This page https://clouddocs.f5.com/containers/v2/releases_and_versioning.html only has info up to version 1.10 of CIS.

**Comment by pdp2shirts** [comment]
@rsalsa @trinaths Can this be updated as part of the 1.11.1 release.

**Comment by ssurenr** [comment]
Thanks, @pdp2shirts. We'll update this in 1.11.1.

**Comment by pdp2shirts** [comment]
Looks like this issue can be closed as the release notes have been updated...
